# -*- coding: utf-8 -*-
"""MODEL#2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1or_7UKR8OEEmPI0Nv2RuqQAsLBhtXgwq
"""

import pandas as pd
import streamlit as st
st.title("Frisco House Price Predictor")
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import TweedieRegressor
from sklearn.metrics import mean_squared_error, r2_score

import streamlit as st


# 1. Load and Clean Data
df = pd.read_csv('frisco_houses.csv')
df = df.drop(0) # Remove the header/disclaimer row

# Select features and target
features = ['BEDS', 'BATHS', 'SQUARE FEET', 'LOT SIZE', 'YEAR BUILT', 'ZIP OR POSTAL CODE']
target = 'PRICE'

# Drop rows with missing values in our selected columns
df_clean = df[features + [target]].dropna()

# 2. Preprocessing
# Convert Zip Code to string to treat it as a category, then One-Hot Encode
df_clean['ZIP OR POSTAL CODE'] = df_clean['ZIP OR POSTAL CODE'].astype(str)
df_final = pd.get_dummies(df_clean, columns=['ZIP OR POSTAL CODE'], drop_first=True)

# Remove homes over $2 million to make model smarter
df_clean = df_clean[df_clean['PRICE'] < 2000000]

# Split into X (features) and y (target)
X = df_final.drop(target, axis=1)
y = df_final[target]

# 3. Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Scaling Numerical Features
scaler = StandardScaler()
# We only scale the non-dummy columns
num_cols = ['BEDS', 'BATHS', 'SQUARE FEET', 'LOT SIZE', 'YEAR BUILT']
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

# 5. Build the GLM (Gamma Regressor with Log Link)
# power=2 corresponds to Gamma distribution, which is ideal for house prices
model = TweedieRegressor(power=2, link='log', max_iter=1000)
model.fit(X_train, y_train)

# 6. Evaluation
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Model Performance:")
print(f"Mean Squared Error (MSE): {mse:,.2f}")
print(f"Root Mean Squared Error (RMSE): ${np.sqrt(mse):,.2f}")
print(f"R-squared Score: {r2:.4f}")

# 7. Prediction Function for Users
def predict_house_price(beds, baths, sqft, lot_size, year_built, zip_code):
    # Initialize as float so we don't get the dtype error
    input_data = pd.DataFrame(0.0, columns=X.columns, index=[0]) 

    input_data.at[0, 'BEDS'] = float(beds)
    input_data.at[0, 'BATHS'] = float(baths)
    
    # Fill in the values
    input_data.at[0, 'BEDS'] = beds
    input_data.at[0, 'BATHS'] = baths
    input_data.at[0, 'SQUARE FEET'] = sqft
    input_data.at[0, 'LOT SIZE'] = lot_size
    input_data.at[0, 'YEAR BUILT'] = year_built

    # Set the zip code dummy variable to 1
    zip_col = f'ZIP OR POSTAL CODE_{float(zip_code)}'
    if zip_col in input_data.columns:
        input_data.at[0, zip_col] = 1

    # Scale numerical values
    input_data[num_cols] = scaler.transform(input_data[num_cols])

    # Predict
    prediction = model.predict(input_data)[0]
    return prediction

    # Create input widgets
    beds = st.number_input("Beds", min_value=1, value=4)
    baths = st.number_input("Baths", min_value=1, value=3)
    sqft = st.number_input("Square Feet", min_value=500, value=2500)
    # ... add other inputs ...

    if st.button("Predict Price"):
        price = predict_house_price(beds, baths, sqft, ...)
        st.success(f"The estimated price is: ${price:,.2f}")

# 1. Create the input fields
# These create the boxes where people can "paste" their own data
beds = st.number_input("Number of Beds", min_value=1, value=4)
baths = st.number_input("Number of Baths", min_value=1, value=3)
sqft = st.number_input("Square Footage", min_value=500, value=2500)
lot_size = st.number_input("Lot Size (sqft)", min_value=1000, value=5000)
year_built = st.number_input("Year Built", min_value=1900, value=2020)
zip_code = st.text_input("Zip Code", value="75033")

# 2. Add a button to trigger the prediction
if st.button("Calculate Estimated Price"):
    # Call your prediction function here
    prediction = predict_house_price(beds, baths, sqft, lot_size, year_built, zip_code)
    
    # 3. Show the result
    st.subheader(f"Estimated Price: ${prediction:,.2f}")
    st.balloons() # Just for fun!


# Example Usage:
example_price = predict_house_price(beds=5, baths=5.5, sqft=5117, lot_size=10846, year_built=2024, zip_code=75033)
print(f"\nEstimated Price for a 4-bed, 3-bath house in 75035: ${example_price:,.2f}")
